### ISSUE TITLE
large space between the cards

### ISSUE THREAD

**Issue by wesleyallanwork** [wesleyallan/carnaval-searcher#2]
# Device
- Desktop
- OS: Windows 11
- Browser: Edge
- Version: 111.0.1661.36

# Describe the bug
Large spaces between the cards

# To Reproduce
1. Go to 'Dev Tools'
2. Rezise viewport

# Expected behavior
That the cards are resized reducing the space between

# Screenshots
![image](https://user-images.githubusercontent.com/127423928/224116373-3971fa17-1e75-4bc5-aed0-73bff8d7adc0.png)

**Comment by wesleyallan** [comment]
# Analise
O erro acontece, pois, possui um valor fixo no tamanho dos cards.
