### ISSUE TITLE
broken input icon

### ISSUE THREAD

**Issue by wesleyallanwork** [wesleyallan/carnaval-searcher#3]
# Device
Desktop
OS: Windows 11
Browser: Edge
Version: 111.0.1661.36

# Describe the bug
Input icon not showing

# To Reproduce
1. Look at form inputs

# Expected behavior
The icon to be displayed

# Screenshots
![image](https://user-images.githubusercontent.com/127423928/224145851-12e9a83e-6bb5-4cda-8d90-b36041ccecd5.png)

**Comment by wesleyallan** [comment]
# Analise
O bug é causado devido ao nome conflitante da importação do ícone.
