### ISSUE TITLE
adicionar animação com scroll.

### ISSUE THREAD

**Issue by wesleyallanwork** [wesleyallan/carnaval-searcher#6]
# ⚠️ Problem
Puramente estético.

# 💡 Idea
Técnica muito utilizada hoje em dia é a de carregar com animação os elementos quando os mesmo estarão visíveis no viewport.

**Comment by wesleyallan** [comment]
# 🔎 Analise
Criar um observador através da Web API Intersection Observer, e animar os mesmo após metade do elemento estar dentro da _viewpoert_
